# Generated by Django 2.1.5 on 2019-01-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=45)),
                ('chat_id', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
